/*
**
** Aero Jail Controler Plugin
** Shared Shared Plugin Base Include
** Author: _AeonOne_
**
** binding license: GPLv3
** voluntary license:
** "THE BEER-WARE LICENSE" (Revision 43-1 by Julien Kluge):
** Julien Kluge wrote this file. As long as you retain this notice you
** can do what is defined in the binding license (GPLv3). If we meet some day, and you think
** this stuff is worth it, you can buy me a beer, pizza or something else which you think is appropriate.
** This license is a voluntary license. You don't have to observe it.
**
*/
#if defined _AC_SHAREDPB_included
	#endinput
#endif
#define _AC_SHAREDPB_included

#include "AC_ClientSys.inc"
#include "AC_ErrorSys.inc"
#include "AC_GameSys.inc"
#include "AC_UISys.inc"